language: python
python:
- '3.2'
- '3.3'
- '3.4'
- '3.5'
before_install:
  pip install twine
install: pip install .
script: py.test
deploy:
  provider: script
  script: scripts/deploy.sh
  on:
    branch: master
